version: '3.7'

services:
  bff-site:
    image: app-site
    container_name: app-site
    build: .docker/development
    command: yarn start:dev
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/api
    networks:
      - backend

  db:
    image: mongo
    container_name: app-site-db
    restart: always
    volumes:
      - app-site-db-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - backend

volumes:
  app-site-db-data:

networks:
  backend:
    driver: bridge
